### PR TITLE
add simple_crud example

### PR DESCRIPTION
**Pull request by frederikhors**

### CODE REVIEW

**Review by resotto — COMMENTED** [review]
@frederikhors Thank you for your PR.

Although this is very difficult part of thinking, there have already been examples in `internal/app`:
https://github.com/resotto/goilerplate/tree/master/internal/app

You already know how this example is organized but other engineer doesn't yet, so its reading cost can be the same as that of remaining ones.

So does this example need to be added?

Thanks.

**Comment by resotto** [comment]
https://github.com/resotto/goilerplate/issues/2

**Comment by resotto** [comment]
BTW, I may update Goilerplate again and I may make examples more readable at that time.
So this fix might be merged in my mind.

**Comment by frederikhors** [comment]
I think examples are the best way to learn. And if I can learn I can use goilerplate.

**Pull request closed without merging**
